[tool.poetry]
name = "speny"
version = "0.1.0"
description = "Telegram bot for tracking spending."
authors = ["shvixxl <contact@shvix.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "3.0.0.b2"
pydantic = "^1.9.0"
Babel = "^2.9.1"
google-api-python-client = "^2.38.0"
google-auth = "^2.6.0"
google-auth-oauthlib = "^0.5.0"
google-auth-httplib2 = "^0.1.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pylint = "^2.12.2"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MASTER']
extension-pkg-whitelist = "pydantic"
