[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "speny"
version = "0.1.0"
description = "Telegram bot for tracking spending."
license = "MIT"
authors = ["shvixxl <contact@shvix.dev>"]
repository = "https://github.com/shvixxl/speny"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "3.0.0.b3"
pydantic = "^1.9.0"
Babel = "^2.9.1"
google-api-python-client = "^2.38.0"
google-auth = "^2.6.0"
google-auth-oauthlib = "^0.5.0"
google-auth-httplib2 = "^0.1.0"
loguru = "^0.6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
ruff = "^0.0"

[tool.ruff]
select = ["F", "E", "W", "I", "UP", "C4", "B", "RUF"]

[tool.pytest.ini_options]
addopts = [
    "--cov=speny",
    "--cov=tests",
]
