name: Deploying

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Authenticate to Google Cloud Platform
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.IMAGE_NAME }}
          username: _json_key
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.IMAGE_NAME }}

      - name: Deploy Docker image
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE }}
          image: ${{ secrets.IMAGE_NAME }}
          region: ${{ secrets.CLOUD_RUN_REGION }}
          secrets: |
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
