name: Deploying

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://t.me/spenybot
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Heroku Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HEROKU_IMAGE_NAME }}
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.HEROKU_IMAGE_NAME }}

      - name: Deploy Docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
