name: Deploying

on:
  push:
    branches: [main]
    tags: [v*.*.*]

  pull_request:
    branches: [main]

env:
  push: ${{ github.event_name == 'push' }}
  image: ${{ github.repository }}
  registry: ghcr.io

jobs:
  build:
    name: Build${{ env.push && ' and publish ' || ' ' }}Docker image
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login against registry ${{ env.registry }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: extract-docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ env.image }}

      - name: Build${{ env.push && ' and publish ' || ' ' }}Docker image
        uses: docker/build-push-action
        with:
          context: .
          push: ${{ env.push }}
          tags: ${{ id.extract-docker-metadata.outputs.tags }}
          labels: ${{ id.extract-docker-metadata.outputs.labels }}

  deploy:
    name: Deploy Docker image
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build .
