name: CI/CD

on:
  schedule:
    - cron: 0 12 * * 0

  push:
    branches: [main]
    tags: [v*.*.*]

  pull_request:
    branches: [main]

env:
  python_version: 3.10.2

  registry: ghcr.io
  image_name: ${{ github.repository }}

permissions:
  contents: read

jobs:
  test-lint:
    name: Run tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Restore cached poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Restore cached Poetry virtualenv
        id: restore-cached-poetry-virtualenv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ env.python-version }}-virtualenv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.python-version }}-virtualenv-

      - name: Install dependencies
        if: steps.restore-cached-poetry-virtualenv.outputs.cache-hit != 'true'
        working-directory: ${{ env.working-directory }}
        run: |
          poetry install --no-interaction

      - name: Run Pylint
        run: |
          poetry run pylint --fail-under 9 speny tests

      - name: Run pytest
        run: |
          poetry run pytest --cov=speny --cov=tests

  codeql:
    name: Run CodeQL analysis
    needs: [test-lint]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: Build CodeQL
        uses: github/codeql-action/autobuild@v1

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v1

  build:
    name: Build${{ github.event_name != 'pull_request' && ' ' || ' and publish ' }}Docker image
    needs: [test-lint, codeql]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login against ${{ env.registry }} registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: extract-docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.registry }}/${{ env.image_name }}

      - name: Build${{ github.event_name != 'pull_request' && ' ' || ' and push ' }}Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.extract-docker-metadata.outputs.tags }}
          labels: ${{ steps.extract-docker-metadata.outputs.labels }}
