name: Testing

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

env:
  python_version: 3.10.2

permissions:
  contents: read

jobs:
  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Restore cached Poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Restore cached Poetry virtualenv
        id: restore-cached-poetry-virtualenv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ env.python-version }}-virtualenv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.python-version }}-virtualenv-

      - name: Install dependencies
        if: steps.restore-cached-poetry-virtualenv.outputs.cache-hit != 'true'
        working-directory: ${{ env.working-directory }}
        run: |
          poetry install --no-interaction

      - name: Run Pylint
        run: |
          poetry run pylint --fail-under 9 speny tests

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_version }}

      - name: Restore cached poetry installation
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Restore cached Poetry virtualenv
        id: restore-cached-poetry-virtualenv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ env.python-version }}-virtualenv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.python-version }}-virtualenv-

      - name: Install dependencies
        if: steps.restore-cached-poetry-virtualenv.outputs.cache-hit != 'true'
        working-directory: ${{ env.working-directory }}
        run: |
          poetry install --no-interaction

      - name: Run pytest
        run: |
          poetry run pytest --cov=speny --cov=tests

  analyse:
    name: Run analyses
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python

      - name: Build CodeQL
        uses: github/codeql-action/autobuild@v1

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v1

  build:
    name: Run builds
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
